dist: xenial

language: python

branches:
  only:
    - master

#
# Test test matrix is spelled out explicitly here.
#
# For each supported version of Python, we will test with:
#
#  * The first minor version of Twisted for each major version that supports
#    the tested version of Python, covering two years of releases.
#
#  * The current release of Twisted.
#
matrix:
  include:
#    - python: 3.7
#      env: TOXENV=flake8
#    - python: 3.7
#      env: TOXENV=mypy

    - python: 2.7
      env: TOXENV=test-py27

    - python: 3.6
      env: TOXENV=test-py36

    - python: 3.7
      env: TOXENV=test-py37-cov

#    - python: 3.7
#      env: TOXENV=docs
#    - python: 3.7
#      env: TOXENV=docs-linkcheck

  allow_failures:
#    # This depends on external web sites, so it's allowed to fail.
#    - env: TOXENV=docs-linkcheck

install:
  - ./travis/install

script:
  - ./travis/run tox
  
after_success:
  - test $TOXENV = test-py37-cov &&
    coveralls
